services:
  - type: web
    name: theory-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://the-way-to-the-license-chatgpt-server.onrender.com
      - key: NODE_VERSION
        value: 18 